import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "../components/AuthProvider";
import Sidebar from "../components/Sidebar";
import ProfileMenu from "../components/ProfileMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider initialSession={null}>
            <div className="flex min-h-screen">
              <Sidebar />
              <div className="flex-1 flex flex-col">
                <header className="flex items-center justify-end h-16 px-6 border-b border-gray-200 dark:border-zinc-800 bg-white dark:bg-zinc-950">
                  <ProfileMenu />
                </header>
                <main className="flex-1 bg-gray-50 dark:bg-zinc-950 p-6">{children}</main>
              </div>
            </div>
          </AuthProvider>
      </body>
    </html>
  );
}
